package controller

import (
	"backend/pkg"
	"fmt"
	"os"

	"github.com/gin-gonic/gin"
)

// 人才培养追踪上链与查询接口

func Uplink(c *gin.Context) {
	// 与 userID 不同，追踪码取雪花ID从第二位开始的18位。
	// +--------------------------------------------------------------------------+
	// | 1 Bit Unused | 41 Bit Timestamp |  10 Bit NodeID  |   12 Bit Sequence ID |
	// +--------------------------------------------------------------------------+
	autoGeneratedTraceCode := pkg.GenerateID()[1:]
	args := buildArgs(c, autoGeneratedTraceCode)
	if args == nil {
		return
	}
	res, err := pkg.ChaincodeInvoke("Uplink", args)
	if err != nil {
		c.JSON(200, gin.H{
			"message": "uplink failed" + err.Error(),
		})
		return
	}
	c.JSON(200, gin.H{
		"code":              200,
		"message":           "uplink success",
		"txid":              res,
		"student_trace_id":  args[1],
	})
}

// 获取单条培养追踪信息
func GetTraceInfo(c *gin.Context) {
	res, err := pkg.ChaincodeQuery("GetTraceInfo", getTraceCode(c))
	if err != nil {
		c.JSON(200, gin.H{
			"message": "查询失败：" + err.Error(),
		})
		return
	}
	c.JSON(200, gin.H{
		"code":    200,
		"message": "query success",
		"data":    res,
	})

}

// 获取当前用户的追踪记录列表
func GetTraceList(c *gin.Context) {
	userID, _ := c.Get("userID")
	res, err := pkg.ChaincodeQuery("GetTraceList", userID.(string))
	if err != nil {
		c.JSON(200, gin.H{
			"message": "query failed" + err.Error(),
		})
	}
	c.JSON(200, gin.H{
		"code":    200,
		"message": "query success",
		"data":    res,
	})
}

// 获取全量培养追踪信息
func GetAllTraceInfo(c *gin.Context) {
	res, err := pkg.ChaincodeQuery("GetAllTraceInfo", "")
	fmt.Print("res", res)
	if err != nil {
		c.JSON(200, gin.H{
			"message": "query failed" + err.Error(),
		})
	}
	c.JSON(200, gin.H{
		"code":    200,
		"message": "query success",
		"data":    res,
	})
}

// 获取追踪记录历史
func GetTraceHistory(c *gin.Context) {
	res, err := pkg.ChaincodeQuery("GetTraceHistory", getTraceCode(c))
	if err != nil {
		c.JSON(200, gin.H{
			"message": "query failed" + err.Error(),
		})
	}
	c.JSON(200, gin.H{
		"code":    200,
		"message": "query success",
		"data":    res,
	})
}

func isAutoGenerateTraceCodeRole(userType string) bool {
	return userType == "学生"
}

func getTraceCode(c *gin.Context) string {
	return c.PostForm("student_trace_id")
}

func buildArgs(c *gin.Context, autoGeneratedTraceCode string) []string {
	var args []string
	userID, _ := c.Get("userID")
	userType, _ := pkg.ChaincodeQuery("GetUserType", userID.(string))
	args = append(args, userID.(string))
	fmt.Print(userID)
	// 学生为起始录入角色，自动生成追踪码。
	if isAutoGenerateTraceCodeRole(userType) {
		args = append(args, autoGeneratedTraceCode)
	} else {
		// 其他角色必须输入有效追踪码
		traceCode := getTraceCode(c)
		res, err := pkg.ChaincodeQuery("GetTraceInfo", traceCode)
		if res == "" || err != nil || len(traceCode) != 18 {
			c.JSON(200, gin.H{
				"message": "请检查学籍追踪码是否正确!!",
			})
			return nil
		} else {
			args = append(args, traceCode)
		}
	}
	args = append(args, c.PostForm("arg1"))
	args = append(args, c.PostForm("arg2"))
	args = append(args, c.PostForm("arg3"))
	args = append(args, c.PostForm("arg4"))
	args = append(args, c.PostForm("arg5"))
	file, _ := c.FormFile("file")
	if file != nil {
		// 保存前端传的图片
		c.SaveUploadedFile(file, "files/uploadfiles/"+file.Filename)
		// 计算文件的SHA256哈希值
		fileSHA256, _ := pkg.CalculateFileSHA256("files/uploadfiles/" + file.Filename)
		ext := pkg.GetFileExt(file.Filename)
		c.SaveUploadedFile(file, fmt.Sprintf("files/images/%s.%s", fileSHA256, ext))
		// 清理临时传的文件
		os.Remove("files/uploadfiles/" + file.Filename)
		args = append(args, fmt.Sprintf("%s.%s", fileSHA256, ext))
	}
	args = append(args, "")
	return args
}

func GetImg(c *gin.Context) {
	filename := c.Param("filename")
	filePath := fmt.Sprintf("files/images/%s", filename)
	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		c.JSON(404, gin.H{
			"message": "file not found",
		})
		return
	}
	c.File(filePath)
}
